car/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment')

    # ex: /home/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),

    # ex: /home/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

my_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),   #hiçbir şey yazılmazsa sitede boşa attık. yinede gitsin home home dersekte çalışır.
    path('home/', include('home.urls')),
    path('car/', include('car.urls')),
    path('user/', include('user.urls')),
    path('reservation/', include('reservation.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('references/', views.references, name='references'),
    path('contact/', views.contact, name='contact'),
    path('category/<int:id>/<slug:slug>/',views.category_cars,name='category_cars'),
    path('car/<int:id>/<slug:slug>/',views.car_detail,name='car_detail'),
    path('search/', views.car_search, name='car_search'),
    path('search_auto/', views.car_search_auto, name='car_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    #path('reservationcart/', reservationviews.reservationcart, name='reservationcart')
    path('sss/', views.faq, name='faq'),

]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #bu kısım olmazsa adminpanelde yüklenen resimleri göstermiyor.

car/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=100,unique=True)
    keywords = models.CharField(blank=True, max_length=255)
    description = models.CharField(blank=True, max_length=255)
    image = models.ImageField(blank=True,upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null="False", unique=True)
    parent = TreeForeignKey('self',blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' >> '.join(full_path[::-1])

    def image_tag(self):    #image ı gösterebilmek için yaptık.urls ede ekleme yaptık.<img src="{}" height="50"/> bu yapı image_tag adında html oluşturuyor.
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

class Car(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE) #relation with Category table.
    title = models.CharField(max_length=150)
    keywords = models.CharField(blank=True, max_length=255)
    description = models.CharField(blank=True, max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField()
    amount = models.IntegerField()
    marka = models.CharField(max_length=30)
    model = models.CharField(max_length=30)
    capacity = models.CharField(max_length=30)
    detail = RichTextUploadingField()
    slug = models.SlugField(null="False", unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):    #image ı gösterebilmek için yaptık.urls ede ekleme yaptık.<img src="{}" height="50"/> bu yapı image_tag adında html oluşturuyor.
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def catimg_tag(self):
        return mark_safe((Category.status))

    def get_absolute_url(self):
        return reverse('car_detail', kwargs={'slug': self.slug})

class Images(models.Model):
    car=models.ForeignKey(Car,on_delete=models.CASCADE)  #biz product yani car dedik kendisi gidip birincil anahtarı oluşturuyor car_id yi.
    title = models.CharField(max_length=50,blank=True)   #etiket title zorunlu değil blank=True ilr yapıyoruz.
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title   #bu fonksiyon title ın adını döndürüyor. save edilince kayıta.

    def image_tag(self):    #image ı gösterebilmek için yaptık.urls ede ekleme yaptık.<img src="{}" height="50"/> bu yapı image_tag adında html oluşturuyor.
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    car = models.ForeignKey(Car,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length=200, blank=True)
    rate = models.IntegerField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment','rate']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)
    catid = forms.IntegerField()

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label= 'User Name ')
    email = forms.EmailField(max_length=200, label= 'Email ')
    first_name = forms.CharField(max_length=100, help_text='First Name', label= 'First Name ')
    last_name = forms.CharField(max_length=100, help_text='Last Name', label= 'Last Name ')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', )

car/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
from car.models import CommentForm, Comment


def index(request):
    return HttpResponse("Car Page")

@login_required(login_url='/login') #check login
def addcomment(request,id):
    url = request.META.get('HTTP_REFERER')  # GET LAST URL
    if request.method == 'POST': #FORM POST EDİLDİYSE
        form = CommentForm(request.POST)
        if form.is_valid():      #car modelsten comment formundan subject rate comment geldi mi kontrol ediyor.
            current_user=request.user  #Access User session information

            data = Comment()           #Model ile bağlantı kuruyor.
            data.user_id = current_user.id
            data.car_id = id
            data.subject =form.cleaned_data['subject']
            data.comment =form.cleaned_data['comment']
            data.rate =form.cleaned_data['rate']
            data.ip =request.META.get('REMOTE_ADDR')  #CLİENT COMPUTER İP ADRESS
            data.save()    #veritabanına kaydettikk.

            messages.success(request, "Yorumunuz başarı ile gönderilmiştir. Teşekkür ederiz.")

            return HttpResponseRedirect(url)
            #return HttpResponse('Kaydedildi.')

    messages.warning(request, "Yorumunuz kaydedilmedi. Lütfen kontrol ediniz.")
    return HttpResponseRedirect(url)

home/views.py
import json
from unicodedata import category

from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

# Create your views here.
from car.models import Car, Category, Images, Comment
from home.forms import SearchForm, SignUpForm
from home.models import Setting, ContactFormu, ContactFormMessage, UserProfile, FAQ


def index(request):       #setting ayarlarını getirecek . artık sitede görünecekler title ı vs.
    setting = Setting.objects.get(pk=1)    #templates in index inde değişiklik yapıldı.
    sliderdata = Car.objects.all()[:4]
    category = Category.objects.all()
    daycars = Car.objects.all()[:4]
    lastcars = Car.objects.all().order_by('-id')[:4]
    randomcars = Car.objects.all().order_by('?')[:4]

    context = {'setting': setting,
               'category': category,
               'page': 'home',
               'sliderdata':sliderdata,
               'daycars': daycars,
               'lastcars': lastcars,
               'randomcars': randomcars,
               'car': Car
               }
    return render(request, 'index.html', context)  #index.htmle gönderdik.

def hakkimizda(request):
    setting = Setting.objects.get(pk=1)
    context = {'setting': setting,
               'category': category,
               'page': hakkimizda,
               }
    return render(request, 'hakkimizda.html', context)

def references(request):
    setting = Setting.objects.get(pk=1)
    context = {'setting': setting,
               'category': category,
               'page': references,
               }
    return render(request, 'references.html', context)

def contact(request):
    if request.method =='POST':                       #FORM POSTT EDİLMİŞ İSE
        form = ContactFormu(request.POST)
        if form.is_valid():
            data = ContactFormMessage()                   #Model ile bağlantı kuruldu.
            data.name = form.cleaned_data['name']     #formdan bilgiyi aldık.
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()                                #veritabanına kaydettikk.
            messages.success(request, "Mesajınız başarılı bir şekilde gönderilmiştir. Teşekkür ederiz.")
            return HttpResponseRedirect('/contact')
    setting = Setting.objects.get(pk=1)
    form = ContactFormu()
    context = {'setting': setting,
               'form': form,
               'category': category,
               'page': contact,
               }
    return render(request, 'contact.html', context)

def category_cars(request,id,slug):
    category = Category.objects.all()
    categorydata = Category.objects.get(pk=id)
    cars = Car.objects.filter(category_id=id, status='True')
    context = {'cars':cars,
               'category': category,
               'categorydata':categorydata
               }
    return render(request,'cars.html',context)

def car_detail(request,id,slug):
    #mesaj="Araç ",id,"/",slug
    category = Category.objects.all()
    car = Car.objects.get(pk=id)
    images = Images.objects.filter(car_id=id)
    comments = Comment.objects.filter(car_id=id, status='True')
    context = {'car': car,
               'category': category,
               'images': images,
               'comments': comments,
               }
    return render(request,'car_detail.html',context)

def car_search(request):
    if request.method == 'POST':   #form post edildiyse
        form = SearchForm(request.POST)
        if form.is_valid():
            category = Category.objects.all()
            query = form.cleaned_data['query']    #formdan bilgiyi al
            catid = form.cleaned_data['catid']

            #cars = Car.objects.filter(title__icontains=query)   #Select * from car where title like %query%
            #return HttpResponse(cars)        #contains li dersek içerir demek ama icontains dersek büyük küçük harf ayrımı yapmadan arama yapacak.

               #get form data

            if catid ==0:
                cars = Car.objects.filter(title__icontains=query)
            else:
                cars = Car.objects.filter(title__icontains=query,category_id=catid)

            context = {'cars': cars,
                       'category': category,
                       }
            return render(request, 'car_search.html', context)

    return HttpResponseRedirect('/')

def car_search_auto(request):
  if request.is_ajax():
    q = request.GET.get('term', '')
    car = Car.objects.filter(title__icontains=q)
    results = []
    for rs in car:
        car_json = {}
        car_json = rs.title
        results.append(car_json)
    data = json.dumps(results)
  else:
    data = 'fail'
  mimetype = 'application/json'
  return HttpResponse(data, mimetype)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, "Login Hatası ! Kullanıcı Adı veya Şifre Yanlış")
            return HttpResponseRedirect('/login')

    category = Category.objects.all()
    context = {'category': category,
               }
    return render(request, 'login.html', context)

def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)   #formumuzu signup ile ilişkilendirdik.
        if form.is_valid():               #valid kontrolü yaptık. şifre vs. uymuyorsa kurallara buna takılıyor.
            form.save()                   #kurallar dolu mu boş mu şifreler aynı mı uyuyor mu vs. dorm.save ile tüm elemanları alıp eşleştirdik.
            #return HttpResponse("Üye kaydedildi.") #kontrol ettim.
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)

            #Create data in profile table for user
            current_user = request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.image = "images/user/user.png"
            data.save()
            messages.success(request, "Hoş Geldiniz.. Sitemize başarılı bir şekilde üye oldunuz. İyi yolculuklar dileriz.")
            return HttpResponseRedirect('/')

    form = SignUpForm()
    category = Category.objects.all()
    context = {'category': category,
               'form': form,
               }
    return render(request, 'signup.html', context)


def faq(request):
    category = Category.objects.all()
    faq = FAQ.objects.all().order_by('ordernumber')
    context = {'category': category,
               'faq': faq,
               }
    return render(request, 'faq.html', context)

home/templates/car_detail.html
{% extends "homebase.html" %}
{% load static %}

{% block title %} {{ car.title }} {% endblock %}
{% block keywords %} {{ car.keywords }} {% endblock %}
{% block description %} {{ car.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block sidebar %}{% include "sidebar.html" %}{% endblock %}

{% block content %}


    <!-- start banner Area -->
    <section class="banner-area relative" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        GetTransfer
                    </h1>
                    <p class="text-white link-nav"><a href="/"> Home </a> <span class="lnr lnr-arrow-right"></span> <a
                            href="blog-home.html"> Transfer Araç Detay </a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="#"> Home >> </a></li>
                <li><a href="#"> Transfer Cars >> </a></li>
                <li><a href="/category/{{ car.category_id }}/{{ car.category.slug }}"> {{ car.category }} >> </a></li>
                <li><a href="#"> {{ car.title }} </a></li>
            </ul>
        </div>
    </div>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <!-- Start model Area -->
    <section class="model-area section-gap" id="cars">
        <div class="container">

            <div class="row d-flex justify-content-center menu-content pb-70">

                <div class="title text-center">
                    <br>
                    <h3 class="mb-10 color-1"> Transferring Car for Your Choices - {{ car.title }}</h3>
                    <hr>
                </div>
            </div>


            <div class="row justify-content-center d-flex align-items-center ">
                <div class="active-model-carusel col-lg-6">

                    <div class="row align-items-center single-model item">
                        <div class="col-lg-12 ">
                            <img class="img-fluid" src="{{ car.image.url }}" alt="">
                        </div>
                    </div>

                    {% for rs in images %}

                        <div class="row align-items-center single-model item">

                            <div class="col-lg-12 ">
                                <img class="img-fluid" src="{{ rs.image.url }}" alt="">
                            </div>
                        </div>

                    {% endfor %}

                </div>


                <div class="col-md-4">

                    <div class="content-wrap">
                        <!--<div class="car-label">
                            <span>New</span>
                            <span class="sale">-%20 </span>
                        </div>
                        -->
                        <h3 class="car-name">{{ car.title }}</h3>
                        <h4 class="car-price">{{ car.price }}
                            <del class="car-old-price">{{ car.price }}</del>
                        </h4>
                        <div class="col-md-7">
                            <a href="#"> Review(s) / Add Review</a>
                        </div>
                        <hr>
                    </div>
                    <p><strong> Availability : </strong> In Now Stock</p>
                    <p><strong> Marka-Model : </strong> GetTransfer</p>
                    <p><strong> Transfer Tanımı : {{ car.description }} </strong></p>
                    <p><strong> Max. Kapasite : {{ car.capacity }} / Bagaj Miktarı : {{ car.amount }}</strong></p>
                    <p><strong> Price : {{ car.price }} / Price of One Person </strong></p>

                    <div class="car-btns">
                        <form action="/reservation/reservationform/{{ car.id }}" method="post">
                            {% csrf_token %}
                            <div class="qty-input">
                                <span class="text-uppercase"> Kişi Sayısı:</span>
                                <input name="quantity" class="input" type="number" min="1" max="{{ car.amount }}"
                                       value="1">
                            </div>
                            <br>

                            <button type="submit" class="primary-btn"><i class="fa fa-car"></i> RESERVE
                            </button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-md-12 section-top-border">
                <div class="tabbable tab-content">
                    <ul class="nav nav-tabs ">

                        <li class="active col-md-2"><a href="#tab1" data-toggle="tab"><i class="icon-briefcase"></i>
                            DETAİLS </a></li>
                        <li class="col-md-2"><a href="#tab2" data-toggle="tab"> REVİEWS </a></li>

                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1">
                            <blockquote class="generic-blockquote">

                                <p>{{ car.detail | safe }}</p>

                            </blockquote>
                        </div>

                        <div class="tab-pane " id="tab2">
                            <blockquote class="generic-blockquote">

                                <div class="row col-md-12">
                                    <div class="col-md-5 model-left">

                                        {% for rs in comments %}

                                            <div class="comment-list left-padding">
                                                <div class="single-comment justify-content-between d-flex">
                                                    <div class="user justify-content-between d-flex">
                                                        <div class="desc">
                                                            <div>
                                                                <a href="#"><i class="fa fa-user-o"></i>
                                                                    <b>{{ rs.user.first_name }}</b></a>
                                                                <p class="date"><i
                                                                        class="fa fa-clock-o"></i> {{ rs.create_at }}
                                                                </p>
                                                            </div>
                                                            <div class="review-rating pull-right">
                                                                <span class="fa fa-star{% if rs.rate < 1 %}-o{% endif %}"></span>
                                                                <span class="fa fa-star{% if rs.rate < 2 %}-o{% endif %}"></span>
                                                                <span class="fa fa-star{% if rs.rate < 3 %}-o{% endif %}"></span>
                                                                <span class="fa fa-star{% if rs.rate < 4 %}-o{% endif %}"></span>
                                                                <span class="fa fa-star{% if rs.rate < 5 %}-o{% endif %}"></span>
                                                            </div>

                                                            <div class="review-body">
                                                                <div style="color:#BC8F8F ">{{ rs.subject }}</div>
                                                                <p>
                                                                    {{ rs.comment }}
                                                                </p>
                                                            </div>
                                                            <hr>

                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        {% endfor %}

                                        <!-- <div class="text-align-left">
                                             <ul class="reviews-pages text-align-left">
                                                 <li class="active" >1</li>
                                                 <li><a href="#">2</a></li>
                                                 <li><a href="#">3</a></li>
                                                 <li><a href="#"><i class="fa fa-caret-right"></i> </a></li>
                                             </ul>
                                         </div>
                                         -->
                                    </div>


                                    <div class="col-md-7 model-right">
                                        <h5 class="text-center"> Write about your transfer journey with this car. </h5>
                                        <hr>
                                        <br>


                                        <p> Your email address will not be published. </p>

                                        <form class="row flex-row d-flex form-area contact-form text-left"
                                              action="/car/addcomment/{{ car.id }}" method="post">
                                            {% csrf_token %}
                                            <div class="col-lg-8 col-md-6 form-group">
                                                <input name="subject" id="id_subject" placeholder="Subject"
                                                       onfocus="this.placeholder = ''"
                                                       onblur="this.placeholder = 'Enter your Subject'"
                                                       class="input common-input mb-20 form-control" required=""
                                                       type="text">
                                            </div>

                                            <div class="col-lg-8 col-md-6 form-group">
                                                <textarea class=" input form-control mb-10" id="id_comment"
                                                          name="comment" placeholder="Your Review"
                                                          onfocus="this.placeholder = ''"
                                                          onblur="this.placeholder = 'Messege'" required=""></textarea>
                                                <div class="col-md-7 ">
                                                    <div class="star"> YOUR RATING :
                                                        <input type="radio" id="star1" name="rate" value="1"/><label
                                                                for="star1"></label>
                                                        <input type="radio" id="star2" name="rate" value="2"/><label
                                                                for="star2"></label>
                                                        <input type="radio" id="star3" name="rate" value="3"/><label
                                                                for="star3"></label>
                                                        <input type="radio" id="star4" name="rate" value="4"/><label
                                                                for="star4"></label>
                                                        <input type="radio" id="star5" name="rate" value="5"/><label
                                                                for="star5"></label>
                                                    </div>
                                                </div>
                                            </div>

                                            {% if user.id is not None %}

                                                <div>
                                                    <br>
                                                    <button class="primary-btn mb-20">Send Comment</button>
                                                </div>

                                            {% else %}
                                                <p>Yorum eklemek için <a href="/login">Login</a> olunuz.</p>
                                            {% endif %}

                                        </form>
                                    </div>
                                </div>
                            </blockquote>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
    <!-- End model Area -->

{% endblock %}

home/templates/contact.html
{% extends "homebase.html" %}

{% block title %} Contact-{{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}    <!--bu homebase deki alana yazılırsa kullanıcı değiştiremez. adminden değişebilecek hale getirdik.-->
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
{% endblock %}

{% block sidebar %}{% include "sidebar.html" %}{% endblock %}
{% block content %}

    <!-- start banner Area -->
    <section class="banner-area relative" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12" >
                    <h1 class="text-white">
                        GetTransfer
                    </h1>
                    <p class="text-white link-nav"><a href="/"> Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="/contact"> Contact </a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->
    <!-- Start blog-posts Area -->
    <section class="blog-posts-area section-gap">
        <div class="container">
            <div class="row ">
                <div class="col-md-4 ">
                    <p><b><font color="#8a2be2" >Bize Ulaşın.. </font></b></p>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}" role ="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form action="" method="post"  class="form-area contact-form text-left">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="SEND MESSAGE">
                    </form>
                </div>
                <div class="col-md-8">
                    {{ setting.contact|safe }}
                </div>

            </div>
        </div>
    </section>
    <!-- End blog-posts Area -->

{% endblock %}