car/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment')

    # ex: /home/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

my_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),   #hiçbir şey yazılmazsa sitede boşa attık. yinede gitsin home home dersekte çalışır.
    path('home/', include('home.urls')),
    path('car/', include('car.urls')),
    path('user/', include('user.urls')),
    path('reservation/', include('reservation.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('references/', views.references, name='references'),
    path('contact/', views.contact, name='contact'),
    path('category/<int:id>/<slug:slug>/',views.category_cars,name='category_cars'),
    path('car/<int:id>/<slug:slug>/',views.car_detail,name='car_detail'),
    path('search/', views.car_search, name='car_search'),
    path('search_auto/', views.car_search_auto, name='car_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    #path('reservationcart/', reservationviews.reservationcart, name='reservationcart')
    path('sss/', views.faq, name='faq'),

]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #bu kısım olmazsa adminpanelde yüklenen resimleri göstermiyor.

reservation/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('reservationcar/<int:id>', views.reservationcar, name='reservationcar'),
    path('reservationform/<int:id>', views.reservationform, name='reservationform'),
    path('reservationcompleted/<int:id>', views.reservationcompleted, name='reservationcompleted'),
]

reservation/models.py
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.forms import ModelForm

from car.models import Car


class Reservation(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    CHOICE = (
        ('Havalimani', 'Havalimani'),
        ('Havalimani-*', 'Havalimani-*'),
        ('Sehir-A', 'Sehir-A'),
        ('Sehir-B', 'Sehir-B'),
        ('Sehir-C', 'Sehir-C'),
        ('-', '-'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    quantity = models.IntegerField()
    date = models.DateTimeField(blank=True)
    time = models.TimeField(blank=True)
    take_off = models.CharField(blank=True, max_length=20, choices=CHOICE, default='-')
    arrive = models.CharField(blank=True, max_length=20, choices=CHOICE, default='-')
    price = models.FloatField()
    status = models.CharField(max_length=20, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name


class ReservationForm(ModelForm):
    class Meta:
        model = Reservation
        fields = ['first_name', 'last_name', 'phone', 'quantity','address','city', 'date', 'time', 'take_off', 'arrive', 'country','price']


class ReservationCar(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )

    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    amount = models.FloatField()
    date = models.DateTimeField(blank=True)
    price = models.FloatField()
    status = models.CharField(max_length=20, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.car.title

reservation/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
# Create your views here.
from django.utils.crypto import get_random_string

from car.models import Category, Car
from home.models import UserProfile
from reservation.models import Reservation, ReservationForm, ReservationCar


#from reservation.models import ReservationCartForm, ReservationCart,

def index(request):
    return HttpResponse("Reservation App")  # döngümün tamamlanıp tamamlanmadığını bu şekilde kontrol edebilirim.


@login_required(login_url='/login')  # Check Login
def reservationcar(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user  # access user session information
    car = Car.objects.get(pk=id)
    carUrl = "/car/" + str(id) + "/" + car.slug
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            data = Reservation()
            data.first_name = current_user.first_name
            data.last_name = current_user.last_name
            data.phone = form.cleaned_data['phone']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.country = form.cleaned_data['country']
            data.date = form.cleaned_data['date']
            data.time = form.cleaned_data['time']
            data.quantity = form.cleaned_data['quantity']
            data.take_off = form.cleaned_data['take_off']
            data.arrive = form.cleaned_data['arrive']
            data.user_id = current_user.id
            data.price = form.cleaned_data['price']
            data.ip = request.META.get('REMOTE_ADDR')
            reservationcode = get_random_string(5).upper()
            data.code = reservationcode
            data.save()

            detail = ReservationCar()
            detail.reservation = data
            detail.car_id = id
            detail.user_id = current_user.id
            detail.quantity = car.amount
            detail.price = car.price
            detail.amount = car.amount
            detail.date = form.cleaned_data['date']
            detail.save()
            car = Car.objects.get(id=id)
            car.amount -= 1
            car.save()

            messages.success(request, "Your reservation has been completed. Thank you'")
            return HttpResponseRedirect("/reservation/reservationcompleted/"+str(data.id))
        else:
            messages.warning(request, "Error <br>" + str(form.errors))
            return HttpResponseRedirect(carUrl)
    else:
        messages.warning(request, "No Post")
        return HttpResponseRedirect(carUrl)


@login_required(login_url='/login')
def reservationform(request, id):
    category = Category.objects.all()
    car = Car.objects.get(pk=id)
    profile = UserProfile.objects.get(user_id=request.user.id)
    total = car.price
    quantity = 1
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if(form.data['quantity'] is not None):
            total=car.price * int(form.data['quantity'])
            quantity = int(form.data['quantity'])
    context = {'id': id,
               'category': category,
               'total': total,
               'quantity': quantity,
               'profile': profile,
               }
    return render(request, 'Reservation_Form.html', context)


def reservationcompleted(request, id):
    category = Category.objects.all()
    reservation = Reservation.objects.get(pk=id)
    context = {
        'category': category, 'reservation': reservation,
    }
    return render(request, 'Reservation_Completed.html', context)

reservation/templates/Reservation_Completed.html
{% extends "homebase.html" %}

{% block title %} Reservation Cart {% endblock %}
{% block keywords %} {{ categorydata.keywords }} {% endblock %}
{% block description %} {{ categorydata.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />
{% endblock %}

{% block sidebar %}{% include "sidebar.html" %}{% endblock %}

{% block content %}

    <!-- start banner Area -->
    <section class="banner-area relative" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12" >
                    <h1 class="text-white">
                        GetTransfer
                    </h1>
                    <p class="text-white link-nav"><a href="/"> Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="/"> Reservation Completed  </a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/"> Home >>  </a></li>
                <li><a href="/"> My Reservation  </a></li>
            </ul>
        </div>
    </div>

    <div class="section">

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                <div>
                    <h3 class="title">Reservation Car List</h3>
                </div>

                    Reservation Completed ! <br>
                    Thank you!<br>
                    Reservation Code : [{{ reservation.code }}] <br>
                    GOOD JOURNEY :)

                </div>
            </div>
        </div>
    </div>

{% endblock %}

reservation/templates/Reservation_Form.html
{% extends "homebase.html" %}

{% block title %} Reservation Form {% endblock %}
{% block keywords %} {{ categorydata.keywords }} {% endblock %}
{% block description %} {{ categorydata.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
{% endblock %}

{% block sidebar %}{% include "sidebar.html" %}{% endblock %}

{% block content %}

    <!-- start banner Area -->
    <section class="banner-area relative" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        GetTransfer
                    </h1>
                    <p class="text-white link-nav"><a href="/"> Home </a> <span class="lnr lnr-arrow-right"></span> <a
                            href="/reservation/reservationform/{{ id }}"> Reservation Form </a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/"> Home >> </a></li>
                <li><a href="/reservation/reservationform/{{ id }}"> Reservation Form </a></li>
            </ul>
        </div>
    </div>

    <div class="section" >

        <div class="container">
            <div class="row">
                    <form action="/reservation/reservationcar/{{ id }}" method="post" class="col-md-12">
                        {% csrf_token %}
                        <div class="col-md-6">
                            <div>
                                <div class="section-title">
                                    <h3 class="title">Reservation Details</h3>
                                </div>

                                <p>
                                    Total Price:{{ total }}
                                </p>

                                <p>
                                    <label for="id_first_name">First Name :</label>
                                    <input type="text" name="first_name" value="{{ user.first_name }}" class="input-group" maxlength="20">
                                </p>
                                <p>
                                    <label for="id_last_name">Last Name :</label>
                                    <input type="text" name="last_name" value="{{ user.last_name }}" class="input-group" maxlength="20">
                                </p>
                                <p>
                                    <label for="id_phone">Phone :</label>
                                    <input type="text" name="phone" value="{{ profile.phone }}" class="input-group" id="id_phone" maxlength="20">
                                </p>
                                <p>
                                    <label for="id_address">Address :</label>
                                    <input type="text" name="address" value="{{ profile.address }}" class="input-group" id="id_address" maxlength="20">
                                </p>
                                <p>
                                    <label for="id_city">City :</label>
                                    <select name="city" class="input-group" id="id_city">
                                        <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                        <option value="İstanbul">İstanbul</option>
                                        <option value="Ankara">Ankara</option>
                                        <option value="İzmir">İzmir</option>
                                        <option value="Kastamonu">Kastamonu</option>
                                        <option value="Bursa">Bursa</option>
                                        <option value="Konya">Konya</option>
                                    </select>
                                </p>
                                <p>
                                    <label for="id_first_name">Country :</label>
                                    <input type="text" name="country" id="id_country" value="{{ profile.country }}" class="input-group" maxlength="20">
                                </p>
                                <p>
                                    <label for="id_date">Date :</label>
                                    <input type="text" name="date" id="datepicker" placeholder="Date & Time" class="dates form-control input-group">
                                </p>
                                <p>
                                    <label for="id_time">Time :</label>
                                    <input type="time" name="time"  id="id_time" placeholder="Time" class=" form-control input-group">
                                </p>
                                <p>
                                    <label for="id_take_off">Take-off :</label>
                                    <select name="take_off" class="input-group" id="id_take_off">
                                        <option value="{{ profile.take_off }}" selected>{{ profile.take_off }}</option>
                                        <option value="Havalimani">Havalimani</option>
                                        <option value="Havalimani-*">Havalimani-*</option>
                                        <option value="Sehir-A">Sehir-A</option>
                                        <option value="Sehir-B">Sehir-B</option>
                                        <option value="Sehir-C">Sehir-C</option>
                                    </select>
                                </p>
                                <p>
                                    <label for="id_arrive">Arrive :</label>
                                    <select name="arrive" class="input-group" id="id_arrive">
                                        <option value="{{ profile.arrive }}" selected>{{ profile.arrive }}</option>
                                        <option value="Havalimani">Havalimani</option>
                                        <option value="Havalimani-*">Havalimani-*</option>
                                        <option value="Sehir-A">Sehir-A</option>
                                        <option value="Sehir-B">Sehir-B</option>
                                        <option value="Sehir-C">Sehir-C</option>
                                    </select>
                                </p>
                            </div>

                        </div>

                        <input name="price"  type="hidden" value="{{ total }}">
                        <input name="quantity"  type="hidden" value="{{ quantity }}">


                        <div class="pull-right">
                            <button type="submit" class="primary-btn">Complete Reservation</button>
                        </div>

                    </form>
            </div>
        </div>
    </div>

{% endblock %}